services:
  mc-manager:
    build: .
    ports:
      - "8080:8080" # Port for Go server
      - "25565:25565" # Port for minecraft server
      - "24454:24454/udp" # Port for Simple Voice Chat mod
    volumes:
      - ./minecraft-server:/app/minecraft-server
      - ./data:/app/data
    restart: unless-stopped
    command: ./server
